import Meaning from './Meaning';

const TABLE = 'MeaningSentence';
const COLUMN_ID = 'meaningsentence_id';
const COLUMN_MEANING_ID = 'meaningsentence_meaning_id';
const COLUMN_TEXT = 'meaningsentence_text';
const COLUMN_DATETIMECREATED = 'meaningsentence_datetimecreated';

const CREATE_MEANINGSENTENCE_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
    COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
    COLUMN_MEANING_ID + " INTEGER NOT NULL, " +
    COLUMN_TEXT + " TEXT NOT NULL, " +
    COLUMN_DATETIMECREATED + " text not null, " +
    "FOREIGN KEY(" + COLUMN_MEANING_ID + ") REFERENCES " + Meaning.TABLE + "(" + Meaning.COLUMN_ID + ") " +
")";
const INSERT_MEANINGSENTENCE_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_MEANING_ID + ", " + COLUMN_TEXT + ", " + COLUMN_DATETIMECREATED + ") VALUES (?, ?, datetime('now'))";
const DELETE_MEANINGSENTENCE_QUERY = "DELETE FROM " + TABLE + " WHERE " + COLUMN_ID + " = ?";
const SELECT_ALL_MEANINGSENTENCE_QUERY = "SELECT * FROM " + TABLE + " WHERE " + Meaning.COLUMN_ID + " = ?";

export default MeaningSentence = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_MEANING_ID: COLUMN_MEANING_ID,
    COLUMN_TEXT: COLUMN_TEXT,
    COLUMN_DATETIMECREATED: COLUMN_DATETIMECREATED,
    Query: {
        CREATE_MEANINGSENTENCE_TABLE: CREATE_MEANINGSENTENCE_TABLE,
        INSERT_MEANINGSENTENCE_QUERY: INSERT_MEANINGSENTENCE_QUERY,
        DELETE_MEANINGSENTENCE_QUERY: DELETE_MEANINGSENTENCE_QUERY,
        SELECT_ALL_MEANINGSENTENCE_QUERY: SELECT_ALL_MEANINGSENTENCE_QUERY,
    }
}