const TABLE = 'Meaning';
const COLUMN_ID = 'meaning_id';
const COLUMN_WORD_ID = 'meaning_word_id';
const COLUMN_TEXT = 'meaning_text';
const COLUMN_WORD_CLASSIFICATION = 'meaning_classification';
const COLUMN_DATETIMECREATED = 'meaning_datetimecreated';

const CREATE_MEANING_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
    COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
	COLUMN_WORD_ID + " INTEGER NOT NULL, " +
	COLUMN_TEXT + " TEXT NOT NULL, " +
	COLUMN_WORD_CLASSIFICATION + " TEXT, " +
	COLUMN_DATETIMECREATED + " TEXT NOT NULL" +
")";
const INSERT_MEANING_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_WORD_ID + ", " + COLUMN_TEXT + ", " + COLUMN_WORD_CLASSIFICATION + ", " + COLUMN_DATETIMECREATED + ") VALUES (?, ?, ?, datetime('now'))";
const DELETE_MEANING_BY_WORD_ID_QUERY = "DELETE FROM " + TABLE + " WHERE " + COLUMN_WORD_ID + " = ?";
const SELECT_ALL_MEANING_QUERY = "SELECT * FROM " + TABLE + " WHERE " + COLUMN_WORD_ID + " = ?";

export default Meaning = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_WORD_ID: COLUMN_WORD_ID,
    COLUMN_TEXT: COLUMN_TEXT,
    COLUMN_WORD_CLASSIFICATION: COLUMN_WORD_CLASSIFICATION,
    COLUMN_DATETIMECREATED: COLUMN_DATETIMECREATED,
    Query: {
        CREATE_MEANING_TABLE: CREATE_MEANING_TABLE,
        INSERT_MEANING_QUERY: INSERT_MEANING_QUERY,
        DELETE_MEANING_BY_WORD_ID_QUERY: DELETE_MEANING_BY_WORD_ID_QUERY,
        SELECT_ALL_MEANING_QUERY: SELECT_ALL_MEANING_QUERY,
    }
}