TABLE = 'Tag';
COLUMN_ID = 'tag_id';
COLUMN_TITLE = 'tag_title';
COLUMN_DATETIMECREATED = 'tag_datetimecreated';

const CREATE_TAG_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
	COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
	COLUMN_TITLE + " TEXT NOT NULL, " +
	COLUMN_DATETIMECREATED + " TEXT NOT NULL" +
")";
const INSERT_TAG_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_TITLE + ", " + COLUMN_DATETIMECREATED + ") VALUES (?, datetime('now'))";
const SELECT_TAGS_QUERY = "SELECT * FROM " + TABLE + " WHERE " + COLUMN_TITLE + " = ?";
const SELECT_ALL_TAGS_QUERY = "SELECT * FROM " + TABLE;

export default Tag = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_TITLE: COLUMN_TITLE,
    COLUMN_DATETIMECREATED: COLUMN_DATETIMECREATED,
    Query: {
        CREATE_TAG_TABLE: CREATE_TAG_TABLE,
        INSERT_TAG_QUERY: INSERT_TAG_QUERY,
        SELECT_TAGS_QUERY: SELECT_TAGS_QUERY,
        SELECT_ALL_TAGS_QUERY: SELECT_ALL_TAGS_QUERY,
    }
}