import Word from './Word';
import Tag from './Tag';

const TABLE = 'WordTag';
const COLUMN_ID = 'wordtag_id';
const COLUMN_WORD_ID = 'wordtag_word_id';
const COLUMN_TAG_ID = 'wordtag_tag_id';
const COLUMN_DATETIMELINKED = 'wordtag_datetimelinked';

const CREATE_WORDTAG_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
	COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
	COLUMN_WORD_ID + " INTEGER NOT NULL, " +
	COLUMN_TAG_ID + " INTEGER NOT NULL, " +
	COLUMN_DATETIMELINKED + " TEXT NOT NULL, " +
	"FOREIGN KEY(" +COLUMN_WORD_ID + ") REFERENCES " + TABLE + "(" + COLUMN_ID + "), " +
	"FOREIGN KEY(" + COLUMN_TAG_ID + ") REFERENCES " + Tag.TABLE + "(" + Tag.COLUMN_ID + ") " +
")";
const INSERT_WORDTAG_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_WORD_ID + ", " + COLUMN_TAG_ID + ", " + COLUMN_DATETIMELINKED + ") VALUES (?, ?, datetime('now'))";
const SELECT_ALL_WORDTAG_QUERY = "SELECT * FROM " + Tag.TABLE + " INNER JOIN " + TABLE + " ON " + Tag.COLUMN_ID + " = " + COLUMN_TAG_ID + " WHERE " + COLUMN_WORD_ID + " = ?";
const SELECT_ALL_TAGWORD_QUERY = "SELECT * FROM " + Word.TABLE + " INNER JOIN " + TABLE + " ON " + Word.COLUMN_ID + " = " + COLUMN_WORD_ID + " WHERE " + COLUMN_TAG_ID + " = ?";
const SELECT_ALL_TAGWORD_ORDERBY_LATEST_QUERY = "SELECT * FROM " + Word.TABLE + " INNER JOIN " + TABLE + " ON " + Word.COLUMN_ID + " = " + COLUMN_WORD_ID + " WHERE " + COLUMN_TAG_ID + " = ? ORDER BY " + COLUMN_DATETIMELINKED + " DESC";

export default WordTag = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_WORD_ID: COLUMN_WORD_ID,
    COLUMN_TAG_ID: COLUMN_TAG_ID,
    COLUMN_DATETIMELINKED: COLUMN_DATETIMELINKED,
    Query: {
        CREATE_WORDTAG_TABLE: CREATE_WORDTAG_TABLE,
        INSERT_WORDTAG_QUERY: INSERT_WORDTAG_QUERY,
        SELECT_ALL_WORDTAG_QUERY: SELECT_ALL_WORDTAG_QUERY,
        SELECT_ALL_TAGWORD_QUERY: SELECT_ALL_TAGWORD_QUERY,
        SELECT_ALL_TAGWORD_ORDERBY_LATEST_QUERY: SELECT_ALL_TAGWORD_ORDERBY_LATEST_QUERY,
    }
}

