import Word from './Word';
import Series from './Series';

const TABLE = 'WordSeries';
const COLUMN_ID = 'wordseries_id';
const COLUMN_TITLE = 'wordseries_title';
const COLUMN_WORD_ID = 'wordseries_word_id';
const COLUMN_SERIES_ID = 'wordseries_series_id';
const COLUMN_DATETIMELINKED = 'wordseries_datetimelinked';

const CREATE_WORDSERIES_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
    COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
	COLUMN_WORD_ID + " INTEGER NOT NULL, " +
	COLUMN_SERIES_ID + " INTEGER NOT NULL, " +
	COLUMN_DATETIMELINKED + " INTEGER NOT NULL, " +
	"FOREIGN KEY(" + COLUMN_WORD_ID + ") REFERENCES " + Word.TABLE + "(" + Word.COLUMN_ID + "), " +
	"FOREIGN KEY(" + COLUMN_SERIES_ID + ") REFERENCES " + Series.TABLE + "(" + Series.COLUMN_ID + ") " +
")";
const SELECT_ALL_WORDSERIES_QUERY = "SELECT * FROM " + Series.TABLE + " INNER JOIN " + TABLE + " ON "  + Series.COLUMN_ID + " = " + COLUMN_SERIES_ID + " WHERE " + COLUMN_WORD_ID + " = ?";
const SELECT_ALL_SERIESWORD_QUERY = "SELECT * FROM " + Word.TABLE + " INNER JOIN " + TABLE + " ON " + Word.COLUMN_ID + " = " + COLUMN_WORD_ID + " WHERE " + COLUMN_SERIES_ID + " = ?";
const INSERT_WORDSERIES_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_WORD_ID + ", " + COLUMN_SERIES_ID + ", " + COLUMN_DATETIMELINKED + ") VALUES (?, ?, datetime('now'))";

export default WordSeries = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_TITLE: COLUMN_TITLE,
    COLUMN_WORD_ID: COLUMN_WORD_ID,
    COLUMN_SERIES_ID: COLUMN_SERIES_ID,
    COLUMN_DATETIMELINKED: COLUMN_DATETIMELINKED,
    Query: {
        CREATE_WORDSERIES_TABLE: CREATE_WORDSERIES_TABLE,
        SELECT_ALL_WORDSERIES_QUERY: SELECT_ALL_WORDSERIES_QUERY,
        SELECT_ALL_SERIESWORD_QUERY: SELECT_ALL_SERIESWORD_QUERY,
        INSERT_WORDSERIES_QUERY: INSERT_WORDSERIES_QUERY,
    }
}