const TABLE = 'Word';
const COLUMN_ID = 'word_id';
const COLUMN_TEXT = 'word_text';
const COLUMN_PRONUNCIATION = 'word_pronunciation';
const COLUMN_ORIGIN = 'word_origin';
const COLUMN_DATETIMEADDED = "word_datetimeadded";

const CREATE_WORD_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
    COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
	COLUMN_TEXT + " TEXT NOT NULL, " +
	COLUMN_PRONUNCIATION + " TEXT, " +
	COLUMN_ORIGIN + " TEXT, " +
	COLUMN_DATETIMEADDED + " TEXT NOT NULL" +
")";
const INSERT_WORD_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_TEXT + ", " + COLUMN_PRONUNCIATION + ", " + COLUMN_ORIGIN + ", " + COLUMN_DATETIMEADDED + ") VALUES (?, ?, ?, datetime('now'))";
const DELETE_WORD_QUERY = "DELETE FROM " + TABLE + " WHERE " + COLUMN_ID + " = ?";
const SELECT_WORD_BY_ID_QUERY = "SELECT * FROM " + TABLE + " WHERE " + COLUMN_ID + " = ?";
const SELECT_WORD_BY_TEXT_QUERY = "SELECT * FROM " + TABLE + " WHERE " + COLUMN_TEXT + " = ?";
const SELECT_ALL_WORD_QUERY = "SELECT * FROM " + TABLE;
const SELECT_ALL_WORD_QUERY_ORDERBY_LATEST = "SELECT * FROM " + TABLE + " ORDER BY " + COLUMN_DATETIMEADDED + " DESC";

export default Word = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_TEXT: COLUMN_TEXT,
    COLUMN_PRONUNCIATION: COLUMN_PRONUNCIATION,
    COLUMN_ORIGIN: COLUMN_ORIGIN,
    COLUMN_DATETIMEADDED: COLUMN_DATETIMEADDED,
    Query: {
        CREATE_WORD_TABLE: CREATE_WORD_TABLE,
        INSERT_WORD_QUERY: INSERT_WORD_QUERY,
        DELETE_WORD_QUERY: DELETE_WORD_QUERY,
        SELECT_WORD_BY_ID_QUERY: SELECT_WORD_BY_ID_QUERY,
        SELECT_WORD_BY_TEXT_QUERY: SELECT_WORD_BY_TEXT_QUERY,
        SELECT_ALL_WORD_QUERY: SELECT_ALL_WORD_QUERY,
        SELECT_ALL_WORD_QUERY_ORDERBY_LATEST: SELECT_ALL_WORD_QUERY_ORDERBY_LATEST,
    }
}