import Word from './Word';
import Meaning from './Meaning';

const TABLE = 'WordSynonym';
const COLUMN_ID = 'wordsynonym_id';
const COLUMN_MEANING_ID = 'wordsynonym_meaning_id';
const COLUMN_WORD_ID = 'wordsynonym_word_id';
const COLUMN_DATETIMELINKED = 'word_synonym_datetimelinked';

const CREATE_WORDSYNONYM_TABLE = "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
    COLUMN_ID + " INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, " +
	COLUMN_WORD_ID + " INTEGER NOT NULL, " +
	COLUMN_MEANING_ID + " INTEGER NOT NULL, " +
	COLUMN_DATETIMELINKED + " TEXT NOT NULL, " +
	"FOREIGN KEY(" + COLUMN_MEANING_ID + ") REFERENCES " + Meaning.TABLE + "(" + Meaning.COLUMN_ID + "), " +
	"FOREIGN KEY(" + COLUMN_WORD_ID + ") REFERENCES " + Word.TABLE + "(" + Word.COLUMN_ID + ") " +
")";
const INSERT_WORDSYNONYM_QUERY = "INSERT INTO " + TABLE + " (" + COLUMN_WORD_ID + ", " + COLUMN_MEANING_ID + ", " + COLUMN_DATETIMELINKED + ") VALUES (?, ?, datetime('now'))";
const SELECT_ALL_WORDSYNONYM_QUERY = "SELECT " + Word.TABLE + ".* FROM " + Word.TABLE + " INNER JOIN " + TABLE + " ON " + Word.COLUMN_ID + " = " + COLUMN_WORD_ID + " WHERE " + COLUMN_MEANING_ID + " = ?";
const SELECT_ALL_SYNONYMWORD_QUERY = "SELECT * FROM " + Meaning.TABLE + " INNER JOIN " + TABLE + " ON " + Meaning.COLUMN_ID + " = " + COLUMN_MEANING_ID + " WHERE " + COLUMN_WORD_ID + " = ?"

export default WordSynonym = {
    TABLE: TABLE,
    COLUMN_ID: COLUMN_ID,
    COLUMN_MEANING_ID: COLUMN_MEANING_ID,
    COLUMN_WORD_ID: COLUMN_WORD_ID,
    COLUMN_DATETIMELINKED: COLUMN_DATETIMELINKED,
    Query: {
        CREATE_WORDSYNONYM_TABLE: CREATE_WORDSYNONYM_TABLE,
        INSERT_WORDSYNONYM_QUERY: INSERT_WORDSYNONYM_QUERY,
        SELECT_ALL_WORDSYNONYM_QUERY: SELECT_ALL_WORDSYNONYM_QUERY,
        SELECT_ALL_SYNONYMWORD_QUERY: SELECT_ALL_SYNONYMWORD_QUERY,
    }
}